### ISSUE TITLE
Nucleotide alignments

### ISSUE THREAD

**Issue by snacktavish** [TheBrownLab/PhyloFisher#101]
Hi PhyloFisher team,
Thanks for sharing your data!
 Do you have available anywhere the nucleotide sequences that went into generating the orthologs sequences provided here?
 https://thebrownlab.github.io/phylofisher-pages/getting-started/download-provided-dataset/
We (me and @JD-X1 ) are interested in comparing mappings an alignments between amino acid and nucleotide data, and it would be valuable comparison dataset for us.
Thanks,

**Comment by atice** [comment]
Hi @snacktavish 

We do have the corresponding nucleotide sequences. They are the subject of new paper we are preparing to submit describing new functionality we are adding to PhyloFisher. I don't see a reason we can't go ahead and pass them along, but we want to check with the PI on the project just to confirm. He will be back early next week from a conference. Could we get back to you then with an answer?

**Comment by snacktavish** [comment]
Sure! That would be great. Thank you!

**Comment by snacktavish** [comment]
Hi, just checking back in on this!
