### ISSUE TITLE
No bootstrap values

### ISSUE THREAD

**Issue by mjamy** [TheBrownLab/PhyloFisher#102]
Hi PhyloFisher team, 

I completed gene tree construction 
(`sgt_constructor.py -i working_dataset_constructor_out_Sep.07.2023 -t 14 -o sgt_constructor_out_Sep.25.2023`). 

I then ran `forest_local.py` on my local machine
(`python forest_local.py -i sgt_constructor_out_Sep.25.2023-local.tar.gz`).

However, when I started parsing the gene trees in ParaSorter, I noticed that none of the trees had any bootstrap values (or rather, all branches are labelled with `1`). 

The `sgt_constructor_out_Sep.25.2023/raxml` directory does contain all the expected output files (including `{gene_name}.raxml.support`). The `sgt_constructor_out_Sep.25.2023/trees` folder on the other hand contains the `{gene_name}.raxml.bestTree` files only. 

I did try replacing the `sgt_constructor_out_Sep.25.2023-local/trees/{gene_name}.raxml.bestTree` files with `{gene_name}.raxml.support` files, compress to get `sgt_constructor_out_Sep.25.2023-local.tar.gz`, and then run `forest_local.py` on it. However, that resulted in an empty `forest_out_Oct.06.2023` folder. 

I'd appreciate any help with this!

Thanks,
Mahwash

**Comment by atice** [comment]
Hi Mahwash,

Thanks for the email. I will not be able to look into this until Monday. Apologies for the delay.

In the meantime can you please send the output of sgt_constructor.py and forest.py to help River and I trouble shoot?

Alex


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Mahwash Jamy ***@***.***>
Sent: Friday, October 6, 2023 8:53:33 AM
To: TheBrownLab/PhyloFisher ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TheBrownLab/PhyloFisher] No bootstrap values (Issue #102)

This email originated outside TTU. Please exercise caution<https://askit.ttu.edu/phishing>!


Hi PhyloFisher team,

I completed gene tree construction
(sgt_constructor.py -i working_dataset_constructor_out_Sep.07.2023 -t 14 -o sgt_constructor_out_Sep.25.2023).

I then ran forest_local.py on my local machine
(python forest_local.py -i sgt_constructor_out_Sep.25.2023-local.tar.gz).

However, when I started parsing the gene trees in ParaSorter, I noticed that none of the trees had any bootstrap values (or rather, all branches are labelled with 1).

The sgt_constructor_out_Sep.25.2023/raxml directory does contain all the expected output files (including {gene_name}.raxml.support). The sgt_constructor_out_Sep.25.2023/trees folder on the other hand contains the {gene_name}.raxml.bestTree files only.

I did try replacing the sgt_constructor_out_Sep.25.2023-local/trees/{gene_name}.raxml.bestTree files with {gene_name}.raxml.support files, compress to get sgt_constructor_out_Sep.25.2023-local.tar.gz, and then run forest_local.py on it. However, that resulted in an empty forest_out_Oct.06.2023 folder.

I'd appreciate any help with this!

Thanks,
Mahwash

**Comment by mjamy** [comment]
Hi Alex, 

Sorry for the delayed response! 

The output files were rather large, so I sent them to you via email. I hope that is okay! 

Thank you for looking into this. 

Mahwash

**Comment by atice** [comment]
Hi Mahwash,

Again, thanks for the email. Robert and I solved the issue, and Robert edited the code to fix the bug. As soon as the new version of PhyloFisher becomes available on Bioconda we will email you with how to proceed. It should be really quick, as you won't have to do a full rerun sgt_constructor.py.


Alex

Alexander K. Tice, Ph.D.
Assistant Professor
Department of Biological Sciences
Texas Tech University
Office: 313
Lab: 308
Phone: (806) 834-6444
________________________________

**Comment by mjamy** [comment]
Great! Thanks Alex and Robert!

**Comment by atice** [comment]
Hi Mahwash,

The PhyloFisher v.1.2.13 is now available from bioconda. After you update, you can proceed either of two ways. You should be able to run forest_local.py on the tar.gz you created after replacing the sgt_constructor_out_Sep.25.2023-local/trees/{gene_name}.raxml.bestTree files with {gene_name}.raxml.support files and get the correct output.

Another way to go about getting the output you need is to delete sgt_constructor_out_Sep.25.2023-local.tar.gz and  sgt_constructor_out_Sep.25.2023/trees/. Then rerun sgt_constructor.py with sgt_constructor_out_Sep.25.2023 provided to the -o flag. This should finish near instantly. Then you will have the correct .tar.gz to provide to forest_local.py.

Let us know if this solves your issue. Thanks for choosing PhyloFisher for your work.

Alex and Robert

**Comment by mjamy** [comment]
Thank you so much! Unfortunately I wont be able to check this until next week, but will let you know if I have any issues. 

Thanks again!
Mahwash

**Comment by mjamy** [comment]
Hi again Alex and Robert, 

I tried following Alex's advice:
> The PhyloFisher v.1.2.13 is now available from bioconda. After you update, you can proceed either of two ways. You should be able to run forest_local.py on the tar.gz you created after replacing the sgt_constructor_out_Sep.25.2023-local/trees/{gene_name}.raxml.bestTree files with {gene_name}.raxml.support files and get the correct output.

But after running `forest_local.py` I get an empty `forest_out` folder. 

Will appreciate any help on how to move forward. 

Thank you!
Mahwash

**Comment by atice** [comment]
Hi Mahwash,

Can you try the second suggestion I made real quick and let us know if that works for you?

Alex

Alexander K. Tice, Ph.D.
Assistant Professor
Department of Biological Sciences
Texas Tech University
Office: 313
Lab: 308
Phone: (806) 834-6444
________________________________

**Comment by mjamy** [comment]
Of course! I did just try it, and I still get an empty `forest_out` folder. 

This is the command I ran on my local machine (M1 Mac):

```
python forest_local.py -i sgt_constructor_out_Sep.25.2023-local.tar.gz
```

Best,
Mahwash

**Comment by atice** [comment]
Thank you for running it. I am bogged down by meetings for the rest of the day. Robert and I will revisit problem tomorrow. Sorry for the inconvenience it has caused.

Alex

Alexander K. Tice, Ph.D.
Assistant Professor
Department of Biological Sciences
Texas Tech University
Office: 313
Lab: 308
Phone: (806) 834-6444
________________________________

**Comment by mjamy** [comment]
Okay thanks! Just to add more info in case it helps troubleshooting, I struggled to install PhyloFisher on the M1 Mac, so to run `forest_local.py`, I've been using the conda environment `forest_local` as described in  #15.

Mahwash

**Comment by atice** [comment]
Hi Mahwash,

forest.py got edited to fix your problem last time but we forgot to make the same changes to forest_local.py. You should now be able to download the corrected version forest_local.py from the GitHub and run it on your sgt_constructor output .tar.gz file. Confirm with us if this fixed your issue or not when you have the chance.

Alex and Robert

**Comment by atice** [comment]
Hi Mahwash,

We cannot recreate your error. Just to make sure you are using the correct version of forest_local.py will you run the attached and let us know if it works. Thanks for your patience.

Alex and Robert

Alexander K. Tice, Ph.D.
Assistant Professor
Department of Biological Sciences
Texas Tech University
Office: 313
Lab: 308
Phone: (806) 834-6444
________________________________

**Comment by mjamy** [comment]
Hi Alex and Robert, 

Turns out it was a mistake on my end.

Happy to report that the problem is fixed, and I am now able to view the trees along with the bootstrap values!!

Thank you for your patience and support. 

Best,
Mahwash

**Comment by atice** [comment]
Great news! Thank you for all your help and patience! Glad you can move forward with your study!

Alex and Robert

Alexander K. Tice, Ph.D.
Assistant Professor
Department of Biological Sciences
Texas Tech University
Office: 313
Lab: 308
Phone: (806) 834-6444
________________________________
