### ISSUE TITLE
sgt_constructor.py "Could not create conda environment from /opt/anaconda3/envs/fisher/bin/bmge.yaml"

### ISSUE THREAD

**Issue by AlexGalvez** [TheBrownLab/PhyloFisher#105]
Hello!

First of all thank you for such an amazing tool!

At the moment I am running Phylofisher v1.2.13 and I am encountering the following error messages (command: sgt_constructor.py -i working_dataset_constructor_out_Oct.24.2023/):

[error_sgt_constructor.txt](https://github.com/TheBrownLab/PhyloFisher/files/13189194/error_sgt_constructor.txt)

Do you have any idea of what can be causing this issue? 
How could I solve it?

Thanks again for your work!

Cheers,

Àlex.

**Comment by atice** [comment]
Hi Alex,

Thank you for contacting us. It will be Monday before Robert and I can sit down to look at this error. I apologize for the inconvenience and the delay. Thank you for choosing PhyloFisher for your work.

Alex

**Comment by AlexGalvez** [comment]
Hi!

No rush at all! Thanks for the support!

Àlex.

**Comment by atice** [comment]
Hi Alex,

If the working nodes on the cluster you are using cannot connect to the internet you may need to submit this first job to the head node just long enough for the dependencies to be installed in the conda env. Once they install just kill the job and submit your real run to the queue. Then from there you should always be able to submit directly to the queue. Sorry for this "hack" suggestion but it should keep you going until we find a longer term solution. Let us know if this does indeed solve the issue.

Alex and Robert

**Comment by AlexGalvez** [comment]
Hi! I think there has been a confusion. I am running Phylofisher in a personal computer with internet access!

Àlex

**Comment by atice** [comment]
Hi Àlex,

Thank you for this information and sorry for the confusion. Could you provide us some information about the specifications of your local machine? Regardless we would highly recommend running this step of the PhyloFisher on a large remote HPCC type resource due to the computational demands it takes to construct that many gene trees with hundreds of sequences under the LG4X model. 

Alex and Robert
