### ISSUE TITLE
forest.py creates an empty folder

### ISSUE THREAD

**Issue by AlexGalvez** [TheBrownLab/PhyloFisher#106]
Hello!

I ran sgt_constructor in my local machine and it generated "sgt_constructor_out_Nov.06.2023" and "sgt_constructor_out_Nov.06.2023-local.tar.gz", but no uncompressed "sgt_constructor_out_Nov.06.2023-local". After that I tried to run forest.py, with the following command "forest.py -i sgt_constructor_out_Nov.06.2023-local.tar.gz -t 14", and it generated an empty folder. What could be causing this behavior?

I also noticed that your documentation says that sgt_constructor will generate files called "RAxML_bipartitions.{gene_name.tre}", but I find files called "{gene_name}.raxml.support". Can this be causing the issue? Am I doing something wrong?

**Comment by atice** [comment]
Hi Alex,

can you confirm you are using the latest version of PhyloFisher (v. 1.2.13) for me? If you are can you add the --local_run flag to your forest.py command and let me know if that solves your problem.

Thank you for catching the error in our documentation. We forgot to update this when we began using RAxML-NG in the workflow. I will make a note to update it.

Let me know if this fixes your issue.

Alex

**Comment by AlexGalvez** [comment]
Hi Alex,

Adding the --local-run flag solved it!

Thanks for the help!

Àlex.
