### ISSUE TITLE
fast_site_remover.py with nucleic acid sequences

### ISSUE THREAD

**Issue by aguang** [TheBrownLab/PhyloFisher#107]
Hi, thanks for this great tool. I used `fast_site_remover.py` to identify my fastest evolving sites for a project I am working on, however I had nucleic acid sequences rather than amino acid sequences. I ended up modifying the script to use nucleic acid sequences and also to print out the indices of the fastest evolving sites both through optional arguments. Would these modifications be of interest to you? If so I can open a pull request with them.

**Comment by atice** [comment]
Hi @aguang 

these sound like great additions to the code! Feel free to open a pull request and when @robert-ervin-jones and I have time we can review your edits and see about making them permanent additions and documenting the new functionality. Thanks for asking!

Alex

**Comment by atice** [comment]
Hi @aguang 

Just wanted to touch base with you on this again. Let us know if you are still interested in providing us with the modifications you have made to our code.

Alex

**Comment by aguang** [comment]
I just made a pull request for it, I think it should have the file modifications
