### ISSUE TITLE
Including BUSCO's metazoa_odb10 dataset

### ISSUE THREAD

**Issue by dongzhang0725** [TheBrownLab/PhyloFisher#108]
Dear developer,

Thank you for developing PhyloFisher. It is an excelent tool. I recently started working on a project that involves studying the phylogeny of Metozoa, and I wonder whether PhyloFisher can work on the BUSCO's metazoa_odb10 dataset. The reason I am sking this is that BUSCO's dataset contains more genes than the dataset curated by PhyloFisher: 954 vs. 240. If it is possible, I would appreciate if you could instruct me how to do it.

Thank you very much!

Sincerely,

Dong

**Comment by atice** [comment]
Hi Dong,

Thank you for your interest in PhyloFisher! Yes, you should be able to create a custom PhyloFisher database from the BUSCO metazoa_odb10 dataset. I will paste the link to our instructions on how to create a custom database below. After you have read through them, let me know if you have any questions. I am happy to help you with however I can.

https://thebrownlab.github.io/phylofisher-pages/getting-started/custom-dataset-prep/

Alex

Alexander K. Tice, Ph.D.
Assistant Professor
Department of Biological Sciences
Texas Tech University
Office: 313
Lab: 308 & 313A
Phone: (806) 834-6444
________________________________
From: zhang dong ***@***.***>
Sent: Friday, November 17, 2023 8:00 PM
To: TheBrownLab/PhyloFisher ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TheBrownLab/PhyloFisher] Including BUSCO's metazoa_odb10 dataset (Issue #108)

This email originated outside TTU. Please exercise caution<https://askit.ttu.edu/phishing>!


Dear developer,

Thank you for developing PhyloFisher. It is an excelent tool. I recently started working on a project that involves studying the phylogeny of Metozoa, and I wonder whether PhyloFisher can work on the BUSCO's metazoa_odb10 dataset. The reason I am sking this is that BUSCO's dataset contains more genes than the dataset curated by PhyloFisher: 954 vs. 240. If it is possible, I would appreciate if you could instruct me how to do it.

Thank you very much!

Sincerely,

Dong

**Comment by dongzhang0725** [comment]
Dear Alex,

Thank you for your quick reply, I will learn this tutorial carefully, and collect related data to give it a try.

Sincerely,
Dong
