### ISSUE TITLE
Trimming question

### ISSUE THREAD

**Issue by lafranco** [TheBrownLab/PhyloFisher#11]
We are working with homologous genes and we want to use PhyloFisher to create the coalescent tree. In the methods of the paper you mentioned that you performed the alignment (MAFFT), then divvier, and then trimming. My question is related to the alignment error analysis than divvier does. We saw that the "-partial" flag is used instead of the "divvy", and then is used trimAl with "-gap threshold = 0.8". I want to understand this step because if we use the "partial" flag we are gonna take some nucleotides that are different within the informative sites and put a gap "-" instead, then trimAl will remove this site ("-"), right?

Thank you for clarify me this,

Augusto Franco

**Comment by robert-ervin-jones** [comment]
Hi Augusto,

Thanks for reaching out.

Phylofisher is not meant for nucleotide data. However if you meant amino acids, divvier using the partial flag will remove some residues replacing them with gaps. Columns that do not meet our trimAl gap threshold after partial filtering with divvier will be removed. If you disagree with out strategy, we have made it possible for you to your own files and renter the workflow after.

I hope this helps. Let me know if you have any other questions.

Best,
Robert
