### ISSUE TITLE
Running PhyloFisher across multiple nodes

### ISSUE THREAD

**Issue by matiasWanntorp** [TheBrownLab/PhyloFisher#110]
Hello! I was wondering whether PhyloFisher supports parallell execution using MPI? Or whether there is some other way of running sgt_constructor.py across multiple nodes at once? Just using one node, with 20 cpus, takes a very long time with the dataset I have. 

All the best and thank you ahead of time!

**Comment by atice** [comment]
Hi @matiasWanntorp,

Unfortunately MPI is not supported in PhyloFisher. One strategy you could take is to break up the output of working_dataset_constructor.py into separate directories. So if each node has 20 cpus you could make 12 directories with 20 genes each. Then, use each of the 12 directories as input for independent runs of sgt_constructor.py. When all runs of sgt_constructor.py finish, merge all sgt_constructor_out_<M.D.Y>/trees directories into one directory and use this for the input of forest.py. Let me know if anything is unclear or if you need help with anything else. Thank you for considering PhyloFisher for your research.

Alex

**Comment by matiasWanntorp** [comment]
Hello again! Thank you for your answer, it makes a lot of sense!
