### ISSUE TITLE
Paralogs added have the exact same name as ortholog

### ISSUE THREAD

**Issue by matiasWanntorp** [TheBrownLab/PhyloFisher#111]
Hello!

I've used "working_dataset_constructor.py" and have all of the multifastas with ortholog, paralogs plus the newly extracted sequences. I noticed that the paralog sequences in my .fas files have identical names to the corresponding ortholog sequences. I wondered whether this is intended or if perhaps something is wrong with my database (custom) or metadata?

Thank you ahead for any insight!

Edit: After looking at the "build_database.py" it seems like the paralogs should be renamed by adding ".." + a random 5 digit number however this doesn't seem to have happened when constructing the database. At least this is my interpretation of the function "paralog_name(abbrev, keys)" in "build_database.py". Could I perhaps do this post database construction and pre "working_dataset_constructor.py"?

**Comment by matiasWanntorp** [comment]
Perhaps I should add, the reason I ask is because of RAxML complaining that there are duplicate names. I'm running RAxML outside of phylofisher.

**Comment by atice** [comment]
HI @matiasWanntorp ,

You are correct that build_database.py should add .." + a random 5 digit number to each sequence header in the paralog files you provide initially. Can you send me an example header or two from your initial fasta file of paralogs?

Alex

**Comment by atice** [comment]
Thanks. We will look into this and get back to you as soon as possible if we need to know anything else to trouble shoot or with debugged code if that is the case.

**Comment by matiasWanntorp** [comment]
Okay, thank you!

**Comment by robert-ervin-jones** [comment]
Hi @matiasWanntorp,

Sorry for just now getting back to you. We are beginning to work on PhyloFisher v2. In the newer version, this will be handled, but for the time being I am going to close this issue.

Thanks for using PhyloFisher!

Best,
Robert
