### ISSUE TITLE
matrix_constructor.py stops at 55 %

### ISSUE THREAD

**Issue by Edouard94** [TheBrownLab/PhyloFisher#119]
Hello team,

A bit of context first, we are trying to produce a preliminary matrix and tree, where we had to speed up our SGTs parsing by deleting the sequences for the one we did not have time to parse yet. But eventually, each ortholog has its parsed tree.

Running apply_to_db.py and prep_final_dataset.py went well (I just had the warning 'There are empty files in the output. Please check for errors'). But when running matrix_constructor.py -i prep_final_dataset_out_Mar.28.2024 -o matrix_constructor_Edouard -t 18, it seems the process always stop when encountering the file nsfNP597649.fas, which looks fine.

```
[Fri Mar 29 10:44:03 2024]
rule remove_gaps:
    input: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_Edouard_concatenate_only/trimal/nsfNP597649.trimal
    output: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_Edouard_concatenate_only/trimal/nsfNP597649.final
    log: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_Edouard_concatenate_only/logs/trimal/nsfNP597649.log
    jobid: 643
    wildcards: gene=nsfNP597649

Job counts:
        count   jobs
        1       remove_gaps
        1
Failed to solve scheduling problem with ILP solver. Falling back to greedy solver. Run Snakemake with --verbose to see the full solver output for debugging the problem.
[Fri Mar 29 10:44:05 2024]
Finished job 643.
536 of 967 steps (55%) done
Exiting because a job execution failed. Look above for error message
Complete log: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/.snakemake/log/2024-03-29T102020.202337.snakemake.log
```

By the way all the trimal and divvier logs are emtpy in the obtained matrix folder.

I attach here the fas file in question [nsfNP597649.txt](https://github.com/TheBrownLab/PhyloFisher/files/14803088/nsfNP597649.txt)  and the complete matrix log [2024-03-29T102020.202337.snakemake.log](https://github.com/TheBrownLab/PhyloFisher/files/14803128/2024-03-29T102020.202337.snakemake.log) and hope you will be able to help me on this issue.

Thank you and my best wishes,
Edouard

**Comment by Edouard94** [comment]
PS: I run PhyloFisher 1.2.12

**Comment by Edouard94** [comment]
EDIT: I try to run matrix_constructor.py without this particular file but it again stopped at step 536 (55 %)

**Comment by atice** [comment]
Hi Edouard,

Thank you for your email. Robert and I will look into this as soon as we can. Just know we may not be as quick as usual. Robert is defending his dissertation in the next few weeks, and I have a full teaching load along with all that is involved in getting my new lab up and running. However, we will try our best to get back to you in a timely manner. As always, thank you for using PhyloFisher in your research.

Alex

Alexander K. Tice, Ph.D.
Assistant Professor
Department of Biological Sciences
Texas Tech University
Office: 313
Lab: 308 & 313A
Phone: (806) 834-6444
________________________________

**Comment by Edouard94** [comment]
Hello Alex,

Thank you for your message. No worries. Good luck to Robert and thank you to look at the issue when you have time. 

Best wishes,
Edouard

**Comment by robert-ervin-jones** [comment]
Hi @Edouard94,

I am unable to find the issue based on the files you shared.

Do you mind sharing the one of the prequal logs for a gene that failed, such as "/home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_Edouard_concatenate_only/logs/prequal/psmc6NP585947.log"?

I apologize for just now getting back to you on this issue.

Best,
Robert

**Comment by Edouard94** [comment]
Hi @robert-ervin-jones,

No worries, thank you for coming back to me and I hope your defense went well!

The matrix script seems to always fail at 55 %, I reran the script and it stopped here:

```Activating conda environment: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/.snakemake/conda/ef33e40ff013e38483a591b14ff8ec4b
/usr/bin/bash: line 1: 304244 Aborted                 (core dumped) prequal /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_out_Apr.30.2024/prequal/rpl13aNP584823.aa > /home/Shared/PhyloFisher>[Tue Apr 30 18:02:44 2024]
Error in rule prequal:
    jobid: 299
    output: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_out_Apr.30.2024/prequal/rpl13aNP584823.aa.filtered
    log: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_out_Apr.30.2024/logs/prequal/rpl13aNP584823.log (check log file(s) for error message)
    conda-env: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/.snakemake/conda/ef33e40ff013e38483a591b14ff8ec4b
    shell:
        prequal /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_out_Apr.30.2024/prequal/rpl13aNP584823.aa >/home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_const>        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/.snakemake/log/2024-04-30T152000.550247.snakemake.log
snakemake -s /home/edouard/miniconda3/envs/fisher/bin/matrix_constructor.smk --config out_dir=/home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_out_Apr.30.2024 in_dir=/home/Shared/PhyloFisher_Mi>Traceback (most recent call last):
  File "/home/edouard/miniconda3/envs/fisher/bin/matrix_constructor.py", line 140, in <module>
    run_snakemake()
  File "/home/edouard/miniconda3/envs/fisher/bin/matrix_constructor.py", line 89, in run_snakemake
    subprocess.run(smk_cmd, shell=True, executable='/bin/bash', check=True)
  File "/home/edouard/miniconda3/envs/fisher/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'snakemake -s /home/edouard/miniconda3/envs/fisher/bin/matrix_constructor.smk --config out_dir=/home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_out_Apr.30>
```

I then attach the corresponding prequal log as you requested Robert, here it was: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_out_Apr.30.2024/logs/prequal/rpl13aNP584823.log --> [rpl13aNP584823.log](https://github.com/TheBrownLab/PhyloFisher/files/15170811/rpl13aNP584823.log)


Let me know if I can share other files and thank you for your help.

Best wishes,
Edouard

**Comment by robert-ervin-jones** [comment]
Hi @Edouard94,

I just noticed you said you got the 'There are empty files in the output. Please check for errors' warning. Did you cleanup the empty files?

Best,
Robert

**Comment by robert-ervin-jones** [comment]
Also, it appears that nsfNP597649 does not error out.

**Comment by Edouard94** [comment]
Hi @robert-ervin-jones,

Thank you for your message.

Yes true I had the error '_There are empty files in the output. Please check for errors_'; well noticed! I continued the workflow without paying attention to that...

I will remove the empty files from prep_final_dataset_out/ (I indeed do have some), and rerun the matrix_constructor script. Hopefully it will fix my issue.

Thank you Robert.

**Comment by Edouard94** [comment]
Hello again @robert-ervin-jones,

I ran again the matrix_constructor without the empty files in prep_final_dataset_out/ and the script almost went through but stopped at 97 % with the following error (snake log):

```
[Tue May  7 14:47:17 2024]
Finished job 182.
452 of 469 steps (96%) done
Select jobs to execute...
Failed to solve scheduling problem with ILP solver. Falling back to greedy solver. Run Snakemake with --verbose to see the full solver output for debugging the problem.

[Tue May  7 14:47:17 2024]
rule remove_gaps:
    input: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_out_May.07.2024/trimal/mcm3NP597158.trimal
    output: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_out_May.07.2024/trimal/mcm3NP597158.final
    log: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_out_May.07.2024/logs/trimal/mcm3NP597158.log
    jobid: 181
    wildcards: gene=mcm3NP597158

^[[33mJob counts:
        count   jobs
        1       remove_gaps
        1^[[0m
^[[33mFailed to solve scheduling problem with ILP solver. Falling back to greedy solver. Run Snakemake with --verbose to see the full solver output for debugging the problem.^[[0m
[Tue May  7 14:47:18 2024]
Finished job 181.
453 of 469 steps (97%) done
Exiting because a job execution failed. Look above for error message
Complete log: /home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/.snakemake/log/2024-05-07T121913.653590.snakemake.log
snakemake -s /home/edouard/miniconda3/envs/fisher/bin/matrix_constructor.smk --config out_dir=/home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_out_May.07.2024 in_dir=/home/Shared/PhyloFisher_Mi>Traceback (most recent call last):
  File "/home/edouard/miniconda3/envs/fisher/bin/matrix_constructor.py", line 140, in <module>
    run_snakemake()
  File "/home/edouard/miniconda3/envs/fisher/bin/matrix_constructor.py", line 89, in run_snakemake
    subprocess.run(smk_cmd, shell=True, executable='/bin/bash', check=True)
  File "/home/edouard/miniconda3/envs/fisher/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'snakemake -s /home/edouard/miniconda3/envs/fisher/bin/matrix_constructor.smk --config out_dir=/home/Shared/PhyloFisher_MicrosporidiainInsectGenomes/Microsporidiatoadd/matrix_constructor_out_May.07>
```
The last trimal job returned an empty log (trimal/mcm3NP597158.log). The fasta file mcm3NP597158 looks normal: [mcm3NP597158.txt](https://github.com/TheBrownLab/PhyloFisher/files/15238019/mcm3NP597158.txt).


Any idea on why the script stopped? Let me know if I can attach some files.

Thank you for your help,
Edouard

**Comment by Edouard94** [comment]
Yes sure, here it is: 
[psma2NP597286.log](https://github.com/TheBrownLab/PhyloFisher/files/15327500/psma2NP597286.log)

**Comment by robert-ervin-jones** [comment]
Hi @Edouard94,

Sorry for just now getting back to you. In this case, you only have one sequence. I would look at prep_final_dataset_out and consider removing genes with that few sequences. 

Best,
Robert

**Comment by Edouard94** [comment]
Hello Robert, 

Sorry for the radio silence, I was finishing my thesis and had a summer break.

Based on your last comment and after filtering out the files with only one sequence, the script is now working fine!

Thanks a lot,
Edouard
