### ISSUE TITLE
'invalid syntax' when running forest_local.py

### ISSUE THREAD

**Issue by cha-namoth** [TheBrownLab/PhyloFisher#15]
Hi guys,

I'm running into an issue with the forest_local.py script on my M1 Mac (another lab member with a M1 Mac has the same issue, although the fact they're Apple Silicon might not be relevant?). We're both running MacOS 12.2 Monterey.

When I try to run:

`python forest_local.py -i sgt_out_DATE.tar.gz`

I get the following error:

```
  File "/Applications/Phylogenetics/forest_local.py", line 61
    help=textwrap.dedent(f"""{in_help}"""))
                                        ^
SyntaxError: invalid syntax
```

Same thing happens if I just try to call `forest_local.py -h`. Running the same command on the same file but with forest.py under a full PhyloFisher installation works without issues.

**Comment by robert-ervin-jones** [comment]
Hi Gordon,

Can you confirm that your python points to python3? I can't recreate this error when using python3, but I can when using python2.

Let me know. If you have any other issues, don't hesitate to reach out.

Best,
Robert

**Comment by cha-namoth** [comment]
Thanks Robert. Didn't event think of that! And MacOS Monterey apparently defaults to its python2 installation... But when I use the python3 installation I get (I'm not in any conda environment either):

```
Traceback (most recent call last):
  File "/Applications/Phylogenetics/forest_local.py", line 13, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'
```

Cheers,
Gordon

**Comment by robert-ervin-jones** [comment]
Okay great!

For this you will need to pip install (or conda if you prefer) matplotlib along with ete3, biopython, and _I think_ argparse.

Thank you for letting me know about this. I don't think the python modules necessary for forest_local.py is documented anywhere. 

Best,
Robert

**Comment by cha-namoth** [comment]
Thanks – I tried installing those in a fresh standard conda environment with python 3.9, but argparse had a conflict and complained it couldn't install into anything higher than python 3.6 (pip without conda also had some issues on my machine).
But after making a conda environment with python 3.6 and installing those modules it runs now! Not sure if there's a workaround to make this work on python >3.6.

Just for anyone who runs into similar issues:

```
conda create --name forest_local python=3.6
conda activate forest_local
conda install matplotlib ete3 biopython argparse
python forest_local.py -i sgt_DATE.tar.gz
```

Cheers,
Gordon

**Comment by robert-ervin-jones** [comment]
Glad you got it work. I now that I think about it I believe argparse is baked into python versions >3.6 which is why it wont let you install it (I just said to try to install argparse because I knew it was a needed module, but forgot about it being baked in). For the record python v3.7.10 is the version all the scripts were written for and what you get when you conda install.

Glad we got it figured out. Going to go ahead and close this issue.
