### ISSUE TITLE
Unable to install PhyloFisher due to dependencies  

### ISSUE THREAD

**Issue by pyongheng** [TheBrownLab/PhyloFisher#22]
Trying to install PhyloFisher I have an error at step 4. 
It is unable to install Prequal. When I manually install Prequal then a second dependency (diamond-0.9.30-h56fc30b_0) was unable to install.
It seems like these dependencies uses different boost-cpp versions.

**Comment by robert-ervin-jones** [comment]
Hi @pyongheng,

Thank you for opening this issue and bringing it to our attention.

Can you please provide some additional information, as I am unable to recreate this problem?

Thanks,
Robert

**Comment by pyongheng** [comment]
[phylofisher_error.txt](https://github.com/TheBrownLab/PhyloFisher/files/8874547/phylofisher_error.txt)

Originally it was not able to install Prequal which is one of the dependency then I manually installed it using "make"
After that, a second dependency (diamond-0.9.30-h56fc30b_0) was unable to install. 
I manually installed it as well but it seems that the dependencies that it uses have conflicting boost-cpp versions with prequal.
Prequal (v 1.74.0*)
diamond-0.9.30-h56fc30b_0 (v 1.70.0*)

**Comment by robert-ervin-jones** [comment]
Hi @pyongheng, 

I apologize for just now getting back to you. 

I have still been unable to recreate this error. Can you confirm that you are using the latest version of `conda`? If you are not using the latest version, can you update it and try again?

I am currently in the process of restructuring the pipelines within PhyloFisher. This will cut down of the number of dependencies that will need to be installed in a single environment. Thus, preventing issues like yours in the future.

Best,
Robert

**Comment by pyongheng** [comment]
Hi @robert-ervin-jones,

I was able to install PhyloFisher on a brand new Mac. 
The problem may have been caused by problems installed in the other system. 
It was using miniconda3 which did not work and I also tried anaconda and miniconda2. 
Thank you for the help. 

Regards,

**Comment by robert-ervin-jones** [comment]
@pyongheng 

Glad you got it intalled. Yes, anaconda2  and any version miniconda will not work at all. It must be anaconda3, preferably installed in your home dir and not system wide.

Going to go ahead and close out the issue since you were able to install PhyloFisher.

Best,
Robert
