### ISSUE TITLE
Unable to install in conda - phylofisher not found

### ISSUE THREAD

**Issue by EricSalomaki** [TheBrownLab/PhyloFisher#23]
We have tried clean installs on multiple computers (Mac and Linux) and are having the same issue on all, see screenshots. 
conda search -f phylofisher is also unable to find the phylofisher package for some reason
I've also run into numerous conflicts in mamba installation can send those if needed as well, but its nearly 8,000 lines long

Separately, pip install phylofisher found v 0.1.3 but the install_deps.py script is not included.

Any help getting fisher installed would be greatly appreciated.

<img width="750" alt="Screen Shot 2022-06-07 at 8 43 42 PM" src="https://user-images.githubusercontent.com/6400723/172968820-45760713-9a55-49d0-96d6-459c7a6b1598.png">
<img width="587" alt="Screen Shot 2022-06-07 at 8 44 05 PM" src="https://user-images.githubusercontent.com/6400723/172968828-fd22c6df-f6ac-4b6a-835b-37d16a732daa.png">

**Comment by robert-ervin-jones** [comment]
Hi @EricSalomaki, 

Thanks for letting me know about this.

In this case, I have not built an osx-arm64 package (M1 macs). I have tried but have been unsuccessful. I am assuming that you have the M1 version of anaconda installed. This seems to not work very well just yet (not just in the case of PhyloFisher), because there are not that many packages for osx-arm64 yet. I have an M1 mac as well but with the standard Anaconda installed, and it works fine. Was the Linux computer you tried on also using an ARM processor?

Best,
Robert

**Comment by EricSalomaki** [comment]
Hi Robert, 

Running the standard Anaconda on the M1 fixed the issues on that computer, thanks for the suggestion. 

The linux computer(s) are servers that have both intel processors and amd gpus and I'm unsure about how the architecture is really set up and where things are being installed, but it was running anaconda 2020.02. There is also an installation of anaconda/3-5.2.0 that we can try in the next week.

Thanks again for your help and I'll let you know how the other anaconda works on the server once we give that a try.

Cheers
Eric

**Comment by robert-ervin-jones** [comment]
@EricSalomaki,

Have you tried again on your Linux machine?

Best,
Robert

**Comment by robert-ervin-jones** [comment]
@EricSalomaki 

I would suggest installing anaconda in your home directory and not using the system wide install. For whatever reason, system wide installs seem to be very problematic. I am also pretty sure that Anaconda recommends avoiding them as well.

Best,
Robert

**Comment by robert-ervin-jones** [comment]
@EricSalomaki

Also, in the future do you mind copying and pasting error messages in a code block or uploading them in a text file. The screenshots are very hard for me to read and have a bright pink background.

Thanks in advance.

-Robert

**Comment by robert-ervin-jones** [comment]
Going to go ahead and close this issue as it seems to be problems with your Anaconda installations and not PhyloFisher specifically.
