### ISSUE TITLE
sgt_constructor.py crashes during least few steps

### ISSUE THREAD

**Issue by cha-namoth** [TheBrownLab/PhyloFisher#5]
Hey guys,

thanks for PhyloFisher – long awaited and I've been super excited to use it. :)

Everything works perfectly until the sgt_constructor.py step – it runs all the filtering, aligning, trimming and tree estimation, but crashes when it tries to copy the results over to the new /tree directory:

```
Waiting at most 5 seconds for missing files.
MissingOutputException in line 165 of /opt/Anaconda3/envs/fisher/bin/sgt_constructor.smk:
Job Missing files after 5 seconds:
```
A bunch of file paths for *.trimmed, *.final, and *.tre files, then:
```
This might be due to filesystem latency. If that is the case, consider to increase the wait time with --latency-wait.
Job id: 2 completed successfully, but some output files are missing. 2
Removing output files of failed job cp_to_trees_dir since they might be corrupted:
/home/glax/Cercozoa/sgt_constructor_out_Aug.23.2021/trees/KDELR2.trimmed, /home/glax/Cercozoa/sgt_constructor_out_Aug.23.2021/trees/GSS.trimmed, /home/glax/Cercozoa/sgt_constructor_out_Aug.23.2021/trees/PSMA-C.trimmed
Job failed, going on with independent jobs.
Exiting because a job execution failed. Look above for error message
Complete log: /home/glax/Cercozoa/.snakemake/log/2021-09-03T114219.940608.snakemake.log
```

The files mentioned don't appear to be corrupted since I can open them, and if I play around with deleting them from all relevant folders, it complains about different files, so I'm not sure what's going on. The script also never creates a tree directory in the output folder.

Any idea what the issue is and how to solve it? 

I should also mention that sgt_constructor.py crashed before because 2 trimal-files (DNAL1 and RF1) had some sequences that were only composed of ambiguous nucleotides (Xs). I deleted those sequences from the trimal files, and reran with the -o flag pointing to the existing directory, that's when I got the above error message. The DNAL1 and RF1 trees were estimated without any issues.

I can provide the full output from the snakemake.log mentioned above if that helps!

Cheers,
Gordon

**Comment by robert-ervin-jones** [comment]
Hi Gordon,

I apologize for the late response. 

We have found and patched a bug in sgt_constructor.py that was causing sequences that only consisted of Xs (as you mention), -s, or a combination of both to not be removed. This led to some unexpected issues downstream.

Please try rerunning again pointing the -o option to the existing output directory.

Let me know if you have any more issues.

Best,
Robert

**Comment by cha-namoth** [comment]
Hi Robert,

thanks – I’ll give it a try as soon as I can and let you know if it works now.

Cheers,
Gordon

**Comment by robert-ervin-jones** [comment]
Hi Gordon, 

I'm assuming this issue has been resolved for you per the latest issue you opened. 

Let me know if that's the case, so I can close out this issue. 

Best,
Robert

**Comment by cha-namoth** [comment]
Hi Robert,

yep, all working now. Sorry for not following up on it!

Cheers,
Gordon
