### ISSUE TITLE
sgt_constructor.py not working, FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by pyongheng** [TheBrownLab/PhyloFisher#55]
Hi, I am getting an error when running sgt_constructor.py on Linux x64.
I can start the run with an M1 mac but with the RAxML problem, it cannot complete correctly. I am also using a larger data set now. 
I am using phylofisher Version: 1.2.0, trying to update using mamba with 'mamba update fisher' returns "All requested packages already installed"

Log of the run. 
[phylofisher2.log](https://github.com/TheBrownLab/PhyloFisher/files/9894990/phylofisher2.log)

config.ini
> 
>   [PATHS]
>   database_folder = /flash/HusnikU/databases/PhyloFisherDatabase_v1.0/database/
>   input_file = /flash/HusnikU/Phua_2/haplozoon/phylofisher/input_metadata.tsv
>   orthomcl = /flash/HusnikU/databases/PhyloFisherDatabase_v1.0/database/orthomcl
>   color_conf = /flash/HusnikU/databases/PhyloFisherDatabase_v1.0/database/tree_colors.tsv

input_metadata.tsv first 5 lines, everything else has the same format
```

Location	File Name	Unique ID	Higher Taxonomy	Lower Taxonomy	Blast Seed	Long Name	Data Type	Source
.	transdecoder.fas	Haplo	Alveolata	Dinoflagellata	none	Haplozoonsp.	Transcriptomic	HaploSmartSeq
.	Abedfoli.fasta	Abedfoli	Alveolata	Dinoflagellata	none	AbediniumfoliumDICHO1703TRINITYpep	Transcriptomic	DICHO1703TRINITYpep
.	Alexande.fasta	Alexande	Alveolata	Dinoflagellata	none	AlexandriumandersoniiCCMP2222EP00969pep	Transcriptomic	Dinodata
.	Alexmarg.fasta	Alexmarg	Alveolata	Dinoflagellata	none	AlexandriummargalefiiCS322MMETSP0661TRINITYpep	Transcriptomic	Dinodata
```

**Comment by robert-ervin-jones** [comment]
Hi @pyongheng,

Let's start with updating phylofisher. The command to do so is `mamba update phylofisher`. Once you get phylofisher updated to the latest version, please try `sgt_constructor.py` again and let us know if it worked.

Best,
Robert

**Comment by pyongheng** [comment]
Hi Robert, 

I was able to update phylofisher. 
 sgt_constructor.py still gives the same error

Thank you

**Comment by pyongheng** [comment]
The code I used is below 

```

sgt_constructor.py -i working_dataset_constructor_out_Oct.30.2022 -t 64

```

before that were these
```

conda activate fisher
fisher.py -t 64 -o fisher_out_Oct.30.2022
informant.py -i fisher_out_Oct.30.2022
working_dataset_constructor.py -i fisher_out_Oct.30.2022 -o working_dataset_constructor_out_Oct.30.2022
```

**Comment by pyongheng** [comment]
I tried it both ways, working daataset files generated from the mac moved to the linux and when that did not work, I restarted the whole process using the linux.

**Comment by atice** [comment]
Could you send us a .tar.gz file of the logs directory in sgt_constructor_out_Oct.30.2022 from the run you started on linux please.

**Comment by atice** [comment]
Could you delete all out directories produced by sgt_constructor.py you have on your linux64 system and rerun the script using the command you provided above and report to us what happens.

**Comment by pyongheng** [comment]
I am getting the same error after removing the folder. 
Logs attached. 

[2022-11-03T123239.644151.snakemake.log](https://github.com/TheBrownLab/PhyloFisher/files/9926386/2022-11-03T123239.644151.snakemake.log)
[phylofisher2.log](https://github.com/TheBrownLab/PhyloFisher/files/9926387/phylofisher2.log)

**Comment by robert-ervin-jones** [comment]
Can you please compress the directory `/flash/HusnikU/Phua_2/haplozoon/phylofisher/sgt_constructor_out_Nov.03.2022/logs` and send it to us?

**Comment by atice** [comment]
@pyongheng 

If no out directories were created, would you be willing to meet with us virtually and share your screen while you run the program to better help us help you. We think this would be the most efficient way for us to diagnose the problem and get you moving forward on your project. Let us know.

Alex and Roberty

**Comment by pyongheng** [comment]
Yes, that would be great. 
May I know when you be a good time for you? 
I am in Japan time zone (GMT+9) but I am flexible about timing.

**Comment by robert-ervin-jones** [comment]
Would 10PM your time (8AM our time) on Tuesday, Nov 8th work for you? Our emails are rej110@msstate.edu and at1422@msstate.edu. If you don't mind, please send us an email with a meeting link (any platform is fine with us). Please let us know ahead of time which platform so we can install the necessary software if need be.

**Comment by pyongheng** [comment]
Traceback (most recent call last):
  File "/home/y/yong-phua/mambaforge-pypy3/envs/fisher/lib/python3.7/site-packages/snakemake/__init__.py", line 780, in snakemake
    keepmetadata=keep_metadata,
  File "/home/y/yong-phua/mambaforge-pypy3/envs/fisher/lib/python3.7/site-packages/snakemake/workflow.py", line 1037, in execute
    logger.run_info("\n".join(dag.stats()))
  File "/home/y/yong-phua/mambaforge-pypy3/envs/fisher/lib/python3.7/site-packages/snakemake/dag.py", line 2159, in stats
    yield tabulate(rows, headers="keys")
  File "/home/y/yong-phua/mambaforge-pypy3/envs/fisher/lib/python3.7/site-packages/tabulate/__init__.py", line 2049, in tabulate
    tabular_data, headers, showindex=showindex
  File "/home/y/yong-phua/mambaforge-pypy3/envs/fisher/lib/python3.7/site-packages/tabulate/__init__.py", line 1471, in _normalize_tabular_data
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/y/yong-phua/mambaforge-pypy3/envs/fisher/lib/python3.7/site-packages/tabulate/__init__.py", line 1471, in <lambda>
    rows = list(map(lambda r: r if _is_separating_line(r) else list(r), rows))
  File "/home/y/yong-phua/mambaforge-pypy3/envs/fisher/lib/python3.7/site-packages/tabulate/__init__.py", line 107, in _is_separating_line
    (len(row) >= 1 and row[0] == SEPARATING_LINE)
  File "/home/y/yong-phua/mambaforge-pypy3/envs/fisher/lib/python3.7/site-packages/snakemake/rules.py", line 1120, in __eq__
    return self.name == other.name and self.output == other.output
AttributeError: 'str' object has no attribute 'name'

**Comment by robert-ervin-jones** [comment]
Hi all. You should now be able to upgrade to PhyloFisher v1.2.3

**Comment by pyongheng** [comment]
Hi, 

Thank you for the update. 
I am getting another error, which I as able to work around by making an envs folder and copying the contents of /home/y/yong-phua/mambaforge-pypy3/envs/fisher/bin
would modifying the sgt_constructor.smk file where "envs/" ln 36, 48, 61, 90, 127, 140, 157, 197 is removed from each of the path work as well? 
I want to avoid duplication as much as possible. 

Thanks!
```

Building DAG of jobs...
WorkflowError:
Failed to open source file /home/y/yong-phua/mambaforge-pypy3/envs/fisher/bin/envs/divvier.yaml
FileNotFoundError: [Errno 2] No such file or directory: '/home/y/yong-phua/mambaforge-pypy3/envs/fisher/bin/envs/divvier.yaml'
```
