### ISSUE TITLE
forest.py crashes half way through

### ISSUE THREAD

**Issue by cha-namoth** [TheBrownLab/PhyloFisher#8]
Hi all,

I’m having an issue with forest.py, after having run sgt_constructor.py successfully. I did run it with the --no_trees flag though and ran my own trees in IQtree, then copied all the relevant files into a new folder and compressed it into a .tar.gz.

When I run forest.py on my own Mac on the compressed file, it runs for a while, produces .tsv and .svg files in the forest_out_DATE folder, racks up a lot of entries in the suspicious.txt files and then crashes with this:

```
python /Applications/Phylogenetics/forest_local.py -t 4 -i sgt_out_Dec.14.2021.tar.gz 
Traceback (most recent call last):
  File "/Applications/Phylogenetics/forest_local.py", line 718, in <module>
    tree_to_tsvg(tree)
  File "/Applications/Phylogenetics/forest_local.py", line 390, in tree_to_tsvg
    format_leaves(backpropagation, contaminants, node, node_style, table, top_ranked, len_dict)
  File "/Applications/Phylogenetics/forest_local.py", line 412, in format_leaves
    para_from_meta(backpropagation, node, org, table, len_dict)
  File "/Applications/Phylogenetics/forest_local.py", line 453, in para_from_meta
    paraf = TextFace(f'{metadata[unique_id]["full"]}_{len_dict[org]}@{org}', fgcolor='blue')
KeyError: 'AcanthFB..p90239'
```

I think the offending gene is COPG2, at least that’s the last file produced. I have 64 .svg and 65 .tsv files. Not entirely sure what went wrong, any idea how to fix this? It's clearly working partly but then chokes. Using the standalone forest_local.py script does the same.

I ran my trees in iqtree instead of RAxML for this, but I’ve started another run with sgt_constructor.py where I have phylofisher do the tree estimation with RAxML as well, to see if that makes a difference, but I doubt it.

Cheers,
Gordon

**Comment by cha-namoth** [comment]
Sorry for the late followup. After updating to PhyloFisher 1.0.14 forest.py works properly now!
I had to rerun sgt_constructor.py and my trees with IQtree, then copied everything into a new folder and compressed it. Running forest.py on my local machine with --local_run worked a charm after that.

I'm going through my trees with parasorter now (great experience so far).

Thanks for fixing this!

**Comment by robert-ervin-jones** [comment]
Awesome! I'm glad to hear that!
