### ISSUE TITLE
forest.py produces an empty directory

### ISSUE THREAD

**Issue by miferg** [TheBrownLab/PhyloFisher#84]
I installed phylofisher through anaconda in linux and began an analysis on 10 genomes of interest with unknown taxonomic affiliations. I created the input_metadata.tsv file following the Detailed Example Workflow and ran the config.py, fisher.py, informant.py, working_dataset_constructor.py, and sgt_constructor.py without issues.

Now I have to use the forest.py script but the output directory "forest_out_Jul.06.2023" is empty (no SVGs nor TSV files) regardless if the --local_run flag was used.

What could be causing this behavior?

Thanks in advance,
Miguel

**Comment by atice** [comment]
Hi Miguel,

Could you provide me with the exact command you ran. Also are you running this on a headless server or your local machine?

Thanks,
Alex

Alexander K. Tice, Ph.D.
Department of Biological Sciences
Mississippi State University
027 Harned Hall
Lab Telephone: 662-325-4008

________________________________
From: Miguel F. Romero ***@***.***>
Sent: Thursday, July 6, 2023 12:26 PM
To: TheBrownLab/PhyloFisher ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [TheBrownLab/PhyloFisher] forest.py produces an empty directory (Issue #84)


I installed phylofisher through anaconda in linux and began an analysis on 10 genomes of interest with unknown taxonomic affiliations. I created the input_metadata.tsv file following the Detailed Example Workflow and ran the config.py, fisher.py, informant.py, working_dataset_constructor.py, and sgt_constructor.py without issues.

Now I have to use the forest.py script but the output directory "forest_out_Jul.06.2023" is empty (no SVGs nor TSV files) regardless if the --local_run flag was used.

What could be causing this behavior?

Thanks in advance,
Miguel

**Comment by miferg** [comment]
Hi Alex,

I ran the previous scripts in a headless server and downloaded the .tar.gz file to my local machine. My local machine runs on linux, so I installed phylofisher using anaconda on it as well. The command that I am using is:
```forest.py --local_run -i sgt_constructor_out_Jul.04.2023-local.tar.gz```

**Comment by robert-ervin-jones** [comment]
Hi Miguel,

Do you get any errors, or is it just an empty directory with no errors?

Best,
Robert

**Comment by atice** [comment]
Will you try/look into two things for me if you don't mind.


  1.  Switch the order of the commands first. -i <input.tar.gz> followed by --local_run
  2.  If that does not work, open the .tar.gz and make sure it has output in it.

Alexander K. Tice, Ph.D.
Department of Biological Sciences
Mississippi State University
027 Harned Hall
Lab Telephone: 662-325-4008

________________________________

**Comment by miferg** [comment]
Hi Robert,

I am not getting any message at all, just the empty output.

Alex:

1. I tried the following command:
```forest.py -i sgt_constructor_out_Jul.04.2023-local.tar.gz --local_run```
With the same result.
2. The .tar.gz is not empty. It has the metadata and color files, as well as the trees directory containing the .final, .raxmlbestTree, and .trimmed files for each gene. All of these files look good.

**Comment by robert-ervin-jones** [comment]
Miguel,

I found a bug in forest.py. It has to do with a recent update to sgt_constructor.py. Your sgt_constructor run should be fine. You will just need to run forest.py again after I can get the bug fixed. I apologize for the headache.

Best,
Robert

**Comment by miferg** [comment]
No problem, it's good to know that the bug has been found. Looking forward to use the updated version of forest.py.
Thanks,
Miguel

**Comment by robert-ervin-jones** [comment]
The bug is now fixed. An update should be available from bioconda in the next few days.

Best,
Robert
