### ISSUE TITLE
Geeting error when trying to run the select_taxa.py script

### ISSUE THREAD

**Issue by robert-ervin-jones** [TheBrownLab/PhyloFisher#87]
<div type='discussions-op-text'>

<sup>Originally posted by **shahed30** July 12, 2023</sup>
Hi all

I encountered an error while attempting to run the select_taxa script. My input command was "select_taxa.py --to_exclude exclude.txt --to_include include.txt". 

In order to build my dataset, I utilized two .txt file containing single column taxa information to include and exclude taxa. Please refer to the attached image.

![Screen Shot 2023-07-12 at 12 45 25](https://github.com/TheBrownLab/PhyloFisher/assets/46806465/82c95d51-7820-4151-84a8-455e5a028232)

```
Traceback (most recent call last):
  File "/opt/anaconda/envs/fisher/bin/select_taxa.py", line 174, in <module>
    matrix = update_df_ortho(matrix)
  File "/opt/anaconda/envs/fisher/bin/select_taxa.py", line 92, in update_df_ortho
    gene, _, include = line.split()
ValueError: too many values to unpack (expected 3)
```

I am using phylofisher ver. 1.2.9. 

I would greatly appreciate any assistance you can provide. Thank you. 

Best 

Shahed

</div>

**Comment by robert-ervin-jones** [comment]
Hi @shashed30,

Can you please provide the command you ran?

Thanks,
Robert

**Comment by shahed30** [comment]
My input command was 

`select_taxa.py --to_exclude exclude.txt --to_include include.txt`

**Comment by robert-ervin-jones** [comment]
Did you run select_orthologs.py first? If so, did you edit select_orthologs.tsv?

**Comment by shahed30** [comment]
I ran select_taxa.py before select_orthologs.py

**Comment by robert-ervin-jones** [comment]
Can you try removing select_orthologs.tsv and re-running select_taxa.py?

**Comment by robert-ervin-jones** [comment]
Hi @shahed30,

I am just checking in to see if this has been resolved.

Best,
Robert

**Comment by shahed30** [comment]
After removing the old select_orthologs.tsv file, I re-ran the
select_taxa.py, now it's working fine. Thank you.



Best


SHAHED
