### ISSUE TITLE
Getting error when running apply_to_db.py

### ISSUE THREAD

**Issue by thesamuanels** [TheBrownLab/PhyloFisher#88]
Hi, I am using phylofisher v1.2.9. I have used it once before but I hadn't encounter the following error then.

I am trying to run the command:
`apply_to_db.py -t 8 -i parasorter_out_Aug.03.2023/ -fi fisher_out_Jul.21.2023/`

parasorter_out_Aug.03.2023 includes all parsed tsv files parsed from single gene trees
fisher_out_Jul.21.2023 is the output folder from the fisher.py step.

The message I am getting:
`Traceback (most recent call last):`
`  File "/opt/Anaconda3/envs/fisher_1.2.9/bin/apply_to_db.py", line 379, in <module>`
`    main()`
`  File "/opt/Anaconda3/envs/fisher_1.2.9/bin/apply_to_db.py", line 325, in main`
`    new_database(table)`
`  File "/opt/Anaconda3/envs/fisher_1.2.9/bin/apply_to_db.py", line 250, in new_database`
`    orthologs, paralogs = parse_table(table)`
`  File "/opt/Anaconda3/envs/fisher_1.2.9/bin/apply_to_db.py", line 163, in parse_table`
`    record = seq_dict[abbrev]`
`KeyError: 'rhaphid2'`

"rhaphid2" is the unique ID of a taxon I wanted to add to the database.  
I have even tried to exclude rhaphid2 by using the "--to_exclude" flag, but that didn't work either. The unique id looks the same everywhere, and I don't understand why that one in particular should be problematic, especially since there is another one called 'rhaphid1'.

EDIT: I have tried to replace the id with another id in a copied folder, and it doesn't seem like the issue is the specific id name.
Additionally, I've just remembered I had issues running forest.py, so back then I used the command: 
`xvfb-run forest.py --local_run -i sgt_out_<DATE>.tar.gz`
Including the xvfb-run part before the command made it work. I don't know why it didn't work without it, since I have just tried again _without_, and now it runs smoothly. I wonder if this can be related to the main error in some ways.

Any idea what the issue might be?
Thanks

**Comment by thesamuanels** [comment]
> Do you know which gene appy_to_db.py is on when the error occurs?

I don't know. Is there a way I can see it?

**Comment by robert-ervin-jones** [comment]
Can you `grep rhaphid2` in `<fisher_dir>/*fas`?

**Comment by thesamuanels** [comment]
> Can you `grep rhaphid2` in `<fisher_dir>/*fas`?

Yes, the string 'rhaphid2' is present within the fasta files' headers multiple times, in multiple files.

**Comment by robert-ervin-jones** [comment]
As I cannot reproduce this error, troubleshooting without your files will be extremely difficult. Do you feel comfortable sharing them with us? If so, my email is robert.ervin.jones@gmail.com.

**Comment by robert-ervin-jones** [comment]
Issue is because you have underscores in your long name

**Comment by thesamuanels** [comment]
I have fixed the issue according to your suggestion and it is finally
working now.
Thank you so much for your help.

Sincerely,
Daniele

Il giorno lun 14 ago 2023 alle ore 07:53 Robert E. Jones <
***@***.***> ha scritto:
