### ISSUE TITLE
forest_local.py creates empty output folder

### ISSUE THREAD

**Issue by anoukwillemsen** [TheBrownLab/PhyloFisher#91]
Hello,

After downloading sgt_constructor_out_<M.D.Y>-local.tar.gz to my local machine I am running the forest.py script  on Ubuntu 22.04.3 with the command: 
python3 forest_local.py -t 3 -i sgt_constructor_out_Aug.16.2023-local.tar.gz

This creates the forest_out_<M.D.Y> folder, however this folder is empty. I do not receive any error or warning messages, and I have not been able to identify the problem yet. 

All the best,

Anouk

**Comment by robert-ervin-jones** [comment]
Hi Anouk,

What version of PhyloFisher are you using? You can find this by running `conda list phylofisher` with the cona environment activte where PhyloFisher is installed. 

Best,
Robert

**Comment by anoukwillemsen** [comment]
Hi Robert,
Thanks for your quick reply. The trees were created with the newest version of PhyloFisher (v.1.2.11). However, I am using the standalone version of forest.py on my own machine. 
Best,
Anouk

**Comment by robert-ervin-jones** [comment]
Hi Anouk,

We just updated the local version of forest.py. If you could re-download it and try again that would be great. I'm not surprised that it didn't work on your server. Funny things start happening when trying to render graphics on headless servers. 

Let me know if you have any more issues. 

Best,
Robert

**Comment by anoukwillemsen** [comment]
Hi Robert,
The updated local version of forest.py worked for me. 
Thanks!
Best,
Anouk
