### ISSUE TITLE
Errors running sgt_constructor.py: `Error in rule prequal`, `Error in rule length_filter_mafft`

### ISSUE THREAD

**Issue by mjamy** [TheBrownLab/PhyloFisher#99]
Hello, 

I'm using Phylofisher version `1.2.11`. I prepared a custom database, and am getting several errors when running `sgt_constructor.py`. An example below:

```
Error in rule length_filter_mafft:
    jobid: 1737
    output: /cluster/projects/nn8118k/mahwash/euk-niche-evolution/00_global_tree/00_data/fisher_to_matrix/sgt_constructor_out_Sep.20.2023/length_filtration/mafft/mcm7.aln
    log: /cluster/projects/nn8118k/mahwash/euk-niche-evolution/00_global_tree/00_data/fisher_to_matrix/sgt_constructor_out_Sep.20.2023/logs/length_filter_mafft/mcm7.log (check log file(s) for error message)
    conda-env: /cluster/projects/nn8118k/mahwash/euk-niche-evolution/00_global_tree/00_data/fisher_to_matrix/.snakemake/conda/56b71125409b5153869b28cac9761feb
    shell:
        mafft --thread 1 --globalpair --maxiterate 1000 --unalignlevel 0.6 /cluster/projects/nn8118k/mahwash/euk-niche-evolution/00_global_tree/00_data/fisher_to_matrix/sgt_constructor_out_Sep.20.2023/prequal/mcm7.aa.filtered >/cluster/projects/nn8118k/mahwash/euk-niche-evolution/00_global_tree/00_data/fisher_to_matrix/sgt_constructor_out_Sep.20.2023/length_filtration/mafft/mcm7.aln 2>/cluster/projects/nn8118k/mahwash/euk-niche-evolution/00_global_tree/00_data/fisher_to_matrix/sgt_constructor_out_Sep.20.2023/logs/length_filter_mafft/mcm7.log
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job length_filter_mafft since they might be corrupted:
/cluster/projects/nn8118k/mahwash/euk-niche-evolution/00_global_tree/00_data/fisher_to_matrix/sgt_constructor_out_Sep.20.2023/length_filtration/mafft/mcm7.aln
```

I've tried running the script several times and always get the same error. 

I've attached the log file of the run.
[2023-09-20T111748.098705.snakemake.log](https://github.com/TheBrownLab/PhyloFisher/files/12674723/2023-09-20T111748.098705.snakemake.log)

Here is the .tar.gz file of the logs directory in sgt_constructor_out_Sep.20.2023 from the run (I started the run again, so there might be some extra files).
[logs.tar.gz](https://github.com/TheBrownLab/PhyloFisher/files/12674826/logs.tar.gz)

Any help would be appreciated! 

Thank you,
Mahwash

**Comment by robert-ervin-jones** [comment]
Hi Mahwash,

Thanks for reaching out. We are not able to resolve this based on the log files alone. Could you share your starting sequence file for POLR2B and mcm7? 

Best,
Robert

**Comment by mjamy** [comment]
Hi Robert, 

Sure! Did you mean the files from the `working_dataset_constructor_out` folder? 

Here they are:
[fasta.tar.gz](https://github.com/TheBrownLab/PhyloFisher/files/12676861/fasta.tar.gz)

Best,
Mahwash

**Comment by atice** [comment]
Hi Mahwash,

Yes these are what we needed. Thank you. We will look into it.

ps Could you give us a bit of insight has to where the genes for your custom database came from. Such as an orthofinder run or all vs all blast and MCL clustering etc.

Thanks,
Alex

**Comment by mjamy** [comment]
Hi Alex, 

Sure. The database is based on the 320-gene dataset from [Strassert et al 2021](https://www.nature.com/articles/s41467-021-22044-z), to which I added more taxa from [Tikhonenkov et al 2022](https://www.nature.com/articles/s41586-022-05511-5). I used the initial fasta files and cleaned fasta files from the studies to separate orthologs and paralogs. 

This is the first time I'm running PhyloFisher on this cluster - so the problem could be related to that!

Thanks,
Mahwash

**Comment by robert-ervin-jones** [comment]
Hi Mahwash,

Both POLR2B and mcm7 finished fine for me. I think something on the cluster may be prematurely terminating the processes. There isn't any error in the logs. They just abruptly end. It would probably be worthwhile to reach out to a system administrator for your cluster and see if they can help you pinpoint what is happening.

Let me know if there is anything else we can help with.

Best,
Robert

**Comment by mjamy** [comment]
Hi again!

Just wanted to post an update. Turns out it was just a stupid mistake on my part, and the error went away when I increased the memory allocation. 

Best,
Mahwash

**Comment by atice** [comment]
Hi Mahwash,

Glad to hear you have it running now! Thanks for the update.

Alex

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
